"""
github_auto.py — AUREM Dev
Auto-create a GitHub repo and push generated project files.

Requires: GITHUB_TOKEN env var with repo creation permissions.

Flow:
  1. create_repo(name, private=True) — creates repo under user/org
  2. push_files(repo_full_name, files) — commits all files
  3. returns {repo_url, clone_url, html_url}
"""
from __future__ import annotations
import base64
import logging
import os
from typing import Optional

import httpx

logger = logging.getLogger(__name__)

GITHUB_TOKEN = os.getenv("GITHUB_TOKEN", "")
GITHUB_API   = "https://api.github.com"
GITHUB_ORG   = os.getenv("GITHUB_ORG", "")  # optional org — uses user if empty


def _headers() -> dict:
    return {
        "Authorization": f"Bearer {GITHUB_TOKEN}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }


async def get_authenticated_user() -> dict:
    async with httpx.AsyncClient(timeout=15) as c:
        r = await c.get(f"{GITHUB_API}/user", headers=_headers())
        r.raise_for_status()
        return r.json()


async def create_repo(
    name: str,
    description: str = "Generated by AUREM Dev",
    private: bool = True,
) -> dict:
    """Create a new GitHub repo. Returns repo object."""
    if not GITHUB_TOKEN:
        raise RuntimeError("GITHUB_TOKEN not set")

    owner = GITHUB_ORG or None
    if owner:
        url = f"{GITHUB_API}/orgs/{owner}/repos"
    else:
        url = f"{GITHUB_API}/user/repos"

    payload = {
        "name": name,
        "description": description,
        "private": private,
        "auto_init": False,
    }

    async with httpx.AsyncClient(timeout=20) as c:
        r = await c.post(url, headers=_headers(), json=payload)
        if r.status_code == 422:
            # Repo already exists — fetch it
            user = await get_authenticated_user()
            login = owner or user["login"]
            r2 = await c.get(f"{GITHUB_API}/repos/{login}/{name}", headers=_headers())
            r2.raise_for_status()
            logger.info(f"[github_auto] repo already exists: {login}/{name}")
            return r2.json()
        r.raise_for_status()
        logger.info(f"[github_auto] created repo: {r.json()['full_name']}")
        return r.json()


async def push_files(
    repo_full_name: str,
    files: list[dict],
    branch: str = "main",
    commit_message: str = "Initial commit — generated by AUREM Dev",
) -> dict:
    """
    Push files to a GitHub repo.
    files: [{"path": "src/App.jsx", "content": "...file content..."}]
    """
    if not GITHUB_TOKEN:
        raise RuntimeError("GITHUB_TOKEN not set")

    pushed = []
    errors = []

    async with httpx.AsyncClient(timeout=30) as c:
        for f in files:
            path    = f["path"]
            content = f["content"]
            encoded = base64.b64encode(content.encode("utf-8")).decode("utf-8")

            url = f"{GITHUB_API}/repos/{repo_full_name}/contents/{path}"

            # Check if file exists (for update sha)
            sha: Optional[str] = None
            try:
                existing = await c.get(url, headers=_headers(), params={"ref": branch})
                if existing.status_code == 200:
                    sha = existing.json().get("sha")
            except Exception:
                pass

            payload: dict = {
                "message": commit_message,
                "content": encoded,
                "branch": branch,
            }
            if sha:
                payload["sha"] = sha

            r = await c.put(url, headers=_headers(), json=payload)
            if r.status_code in (200, 201):
                pushed.append(path)
            else:
                errors.append({"path": path, "status": r.status_code, "error": r.text[:200]})
                logger.warning(f"[github_auto] failed to push {path}: {r.status_code}")

    logger.info(f"[github_auto] pushed {len(pushed)}/{len(files)} files to {repo_full_name}")
    return {
        "ok": len(errors) == 0,
        "repo": repo_full_name,
        "pushed": pushed,
        "errors": errors,
    }


async def create_and_push(
    project_name: str,
    files: list[dict],
    description: str = "Generated by AUREM Dev",
    private: bool = True,
) -> dict:
    """One-shot: create repo + push all files."""
    repo = await create_repo(project_name, description, private)
    result = await push_files(repo["full_name"], files)
    return {
        "ok": result["ok"],
        "repo_url": repo["html_url"],
        "clone_url": repo["clone_url"],
        "full_name": repo["full_name"],
        "pushed": result["pushed"],
        "errors": result["errors"],
    }
